server:
  port: 4070

    
spring:
  datasource:    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    batch:
      initialize-schema: always
    application:
      name: customer-queue-management
PROPERTY_PATH: D:\FinFlowz-qms.yml